version: "3.9"

services:
  client:
    build:
      context: ./client
    container_name: client
    restart: always

  server:
    build:
      context: ./server
    container_name: server
    restart: always
    env_file:
      - .env.production
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - client
      - server

volumes:
  mongo_data:
